name: Enviar dados para API

on:
  workflow_dispatch:

jobs:
  enviar-dados:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Cachear modelo GGUF
        uses: actions/cache@v3
        with:
          path: models/
          key: phi2-model-cache-v1

      - name: Criar pasta models
        run: mkdir -p models

      - name: Baixar modelo (se necessário)
        run: |
          if [ ! -f models/Phi-2.Q4_K_M.gguf ]; then
            wget -O models/Phi-2.Q4_K_M.gguf https://huggingface.co/TheBloke/phi-2-GGUF/resolve/main/phi-2.Q4_K_M.gguf
          else
            echo "Modelo já está presente, não será baixado."
          fi

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar script Python
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: python sprinklr_turing.py