name: Enviar dados para API

on:
  push:
    branches: [ main ]

jobs:
  enviar-dados:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'  # Habilita cache automático do pip

      - name: Cache de modelos do HuggingFace
        uses: actions/cache@v3
        with:
          path: ~/.cache/huggingface
          key: ${{ runner.os }}-huggingface-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-huggingface-

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --cache-dir ~/.cache/pip

      - name: Executar script Python
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          HF_HOME: ~/.cache/huggingface  # Define o local de cache dos modelos
        run: python ai.py